name: "Danger Swift"
on: [push]

jobs:
main:
  name: Danger JS
  runs-on: ubuntu-latest
  
  steps:
    - uses: actions/checkout@v1
    - name: Danger
      uses: danger/swift@2.0.1
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}