name: "Danger Swift - Teste"

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: macos-latest
    name: "Run Danger"
    steps:
      - uses: actions/checkout@v3
      # - name: Build
      #   run: swift build
      - name: Run tests
        run: xcodebuild test -scheme FlowersStore -workspace FlowersStore.xcworkspace -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 12 Pro'
      # - name: Danger
      #   uses: danger/swift@3.3.0
      #   with:
      #       args: --failOnErrors --no-publish-check
      - name: Danger Swift
        run: |
          npm install -g danger
          brew install danger/tap/danger-js
          swift build --target DangerDependencies
          swift run danger-swift ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}