name: "Danger Swift"

on:
  push:
    branches: [ git_actions_config ]
  pull_request:
    branches: [ develop ]

jobs:
  main:
    name: Review, Lint, Verify
    runs-on: macos-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: ruby versions
        run: |
          ruby --version
          gem --version
          bundler --version
        
      - name: ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        run: bundle exec danger --verbose